More explicite message for Exception
goodwix/doctrine-json-odm pull request #24
Opened 2022-02-23 15:25 UTC by chadyred

Hello,

I'm always doing this when an error occur with the serialization.

Thanks for your works

2022-03-07 16:55 UTC, strider2038 requested changes
Please, update the tests. I can't merge until all tests pass.

2022-03-07 16:55 UTC, strider2038 commented on src/Type/ODMType.php
> +            $message = sprintf('Serialization exception occurred for class "%s". (%s)', $this->getEntityClass(), $exception->getMessage());
Hello! Thanks for PR. I'm suggesting another format.

```suggestion
            $message = sprintf('Serialization exception occurred for class "%s": %s.', $this->getEntityClass(), $exception->getMessage());
```

2022-03-07 16:55 UTC, strider2038 commented on src/Type/ODMType.php
> +            $message = sprintf('Deserialization exception occurred for class "%s". (%s)', $this->getEntityClass(), $exception->getMessage());
```suggestion
            $message = sprintf('Deserialization exception occurred for class "%s": %s.', $this->getEntityClass(), $exception->getMessage());
```

2022-03-08 10:42 UTC, chadyred commented
A test won't pass and I don't know why it doesn't find a package : https://github.com/goodwix/doctrine-json-odm/runs/5462396435?check_suite_focus=true

2022-11-30 04:23 UTC, merged